# Generated by Django 4.1.5 on 2024-03-20 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_permission', models.CharField(choices=[('NONE', 'None'), ('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LigninUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lignin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('rejected_papers', models.TextField(blank=True)),
                ('default_permission', models.CharField(choices=[('NONE', 'None'), ('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], max_length=5)),
                ('columns', models.ManyToManyField(blank=True, to='ligninapp.column')),
                ('entries', models.ManyToManyField(blank=True, to='ligninapp.entry')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.column')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ligninapp.ligninuser')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.entry')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReviewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('NONE', 'None'), ('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], max_length=5)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.ligninuser')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssPaperID', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('faln', models.CharField(max_length=100)),
                ('references', models.TextField()),
                ('citations', models.TextField()),
                ('year', models.IntegerField()),
                ('url', models.URLField()),
                ('default_subpaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_of', to='ligninapp.entry')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='entry',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.paper'),
        ),
    ]
