# Generated by Django 4.1.5 on 2024-03-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LigninUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssPaperID', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('faln', models.CharField(max_length=100)),
                ('references', models.TextField()),
                ('citations', models.TextField()),
                ('year', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('rejected_papers', models.TextField(blank=True)),
                ('default_permission', models.CharField(choices=[('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], max_length=5)),
                ('columns', models.ManyToManyField(blank=True, to='ligninapp.column')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.ligninuser')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.column')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ligninapp.ligninuser')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Subpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.paper')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], max_length=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.ligninuser')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='papers',
            field=models.ManyToManyField(blank=True, to='ligninapp.subpaper'),
        ),
        migrations.AddField(
            model_name='column',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.ligninuser'),
        ),
    ]
