# Generated by Django 4.1.5 on 2024-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='creator',
        ),
        migrations.AlterField(
            model_name='question',
            name='default_permission',
            field=models.CharField(choices=[('NONE', 'None'), ('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], max_length=5),
        ),
        migrations.AlterField(
            model_name='questionpermission',
            name='permission',
            field=models.CharField(choices=[('NONE', 'None'), ('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], max_length=5),
        ),
    ]
