# Generated by Django 4.1.5 on 2024-06-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0002_alter_column_default_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='default_permission',
            field=models.CharField(choices=[('NONE', 'None'), ('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], help_text='This currently does not matter', max_length=5),
        ),
    ]
