# Generated by Django 4.1.5 on 2024-03-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ligninapp', '0002_remove_question_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='creator',
        ),
        migrations.AddField(
            model_name='column',
            name='default_permission',
            field=models.CharField(choices=[('NONE', 'None'), ('VIEW', 'View'), ('PROP', 'Propose'), ('MOD', 'Moderate'), ('ADMIN', 'Administrate')], default='NONE', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ligninuser',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lignin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
