# Generated by Django 4.1.5 on 2024-03-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0004_paper_default_subpaper_alter_subpaper_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligninapp.subpaper'),
        ),
    ]
