# Generated by Django 4.1.5 on 2023-02-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0004_question_rejected_papers_alter_paper_sspaperid'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ligninapp.paper'),
            preserve_default=False,
        ),
    ]
