# Generated by Django 4.1.5 on 2025-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0004_uploadedpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpaper',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedpaper',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
