# Generated by Django 4.1.5 on 2023-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0005_value_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
