# Generated by Django 4.1.5 on 2025-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0005_uploadedpaper_author_uploadedpaper_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpaper',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
