# Generated by Django 4.1.5 on 2025-07-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligninapp', '0006_uploadedpaper_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpaper',
            name='citation_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedpaper',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
