# Generated by Django 4.1.5 on 2025-10-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ligninapp", "0007_uploadedpaper_citation_text_uploadedpaper_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="paper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ligninapp.paper",
            ),
        ),
    ]
