# Generated by Django 4.1.5 on 2025-10-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ligninapp", "0008_alter_entry_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="uploaded_paper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="ligninapp.uploadedpaper",
            ),
        ),
    ]
