# Generated by Django 4.1.5 on 2025-10-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligninapp", "0009_entry_uploaded_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="value",
            name="highlights",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
