# Generated by Django 4.1.5 on 2025-11-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligninapp", "0010_value_highlights"),
    ]

    operations = [
        migrations.AddField(
            model_name="value",
            name="edited",
            field=models.BooleanField(
                default=False,
                help_text="If True, block LLM updates for this cell; user edits still allowed.",
            ),
        ),
    ]
