# Generated by Django 4.1.5 on 2025-11-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligninapp", "0011_value_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
